set -g default-terminal $TERM
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

set -g mouse on
set -g base-index 1
set -g detach-on-destroy off
set -g mode-keys vi
set -s set-clipboard on

# status line
set -g status-position top
set -g status-justify left
set -g status-keys vi

#set -g status-left '#{user}@#H : #S | '
set -g status-left ' #S | '
set -g status-left-length 50

#set -g status-right '#{pane_current_path}'
set -g status-right '#{tmux_mode_indicator}'
set -g status-left-length 50

# panes
set -g pane-border-status top
set -g pane-border-format '"#{user}@#H: #{pane_current_path}"'
set -g pane-border-lines single
set -g pane-border-indicators off

unbind %
bind '\' split-window -h

unbind '"'
bind - split-window -v

bind 'j' select-pane -D
bind 'k' select-pane -U
bind 'l' select-pane -R
bind 'h' select-pane -L
bind ';' select-pane -l

# windows
bind 'n' select-window -n
bind 'p' select-window -p
bind ',' select-window -l

bind-key x kill-pane
bind-key q confirm kill-window

# source config file
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'MunifTanjim/tmux-mode-indicator'
set -g @plugin 'MunifTanjim/tmux-suspend'
set -g @suspend_key 'F12'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
unbind '&'
bind '&' run-shell "rm -rf $HOME/.local/share/tmux/resurrect/"

#set -g @plugin 'tmux-plugins/tmux-yank'

#set -g @plugin 'tmux-plugins/tmux-continuum'
#set -g @continuum-restore 'off'

#set -g @plugin 'christoomey/vim-tmux-navigator'
#set -g @plugin 'fabioluciano/tmux-tokyo-night'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "$HOME/.local/tmux-plugins/tpm"

