#!/bin/sh
set -e

download() {
pkgs="
file man powertop
curl telnet axel
bash-completion
command-not-found
progress
vim
xdg-utils
xz-utils
unzip
libxcb-xkb1
gcc
$([ "$(ps -p1 --no-headers -o comm)" = "systemd" ] && echo "" || echo "systemctl")
"
apt install -y --no-install-recommends $pkgs
}

setup() {
  :
}

[ "$(id -u)" = "0" ] && download || setup

