#!/bin/sh
set -e

download() {
  pkgs="
  $([ "$(ps -p1 --no-headers -o comm)" = "systemd" ] && echo "" || echo "elogind")
  xinit xserver-xorg policykit-1
  xfce4-session xfwm4 xfce4-panel xfce4-terminal
  xfce4-notifyd gnome-icon-theme
  xfce4-power-manager-plugins
  pulseaudio xfce4-pulseaudio-plugin
  xfce4-screenshooter xfce4-clipman
  "
  apt purge -y xdg-user-dirs
  apt install -y --no-install-recommends $pkgs
}

setup() {
  grep -q 'clean && startxfce4' "$HOME/.profile" ||
    echo '[[ $(tty) =~ /dev/tty ]] && startxfce4' >>"$HOME/.profile"
}

[ "$(id -u)" = "0" ] && download || setup

