#!/bin/sh
set -e

self="${0%/*}"
[ "$self" = "$0" ] && self="."
. "$self/utils.sh"

usage() {
  cat >&2 <<EOF
Usage: $0 [options]

Options:
  -help      Show this help message
  -force     Force reinstallation
  -version   Version to install (default '$version')
EOF
}

parse_args() {
  platform="linux-amd64"
  version="1.70.3"

  while [ $# -gt 0 ]; do
    case "$1" in
      -help)
        usage
        exit 0
        ;;
      -force)
        force="true"
        shift
        ;;
      -version)
        version="$(get_opt "$@")"
        shift 2
        ;;
      -*) die -h "Unknown option '$1'" ;;
      *) shift ;;
    esac
  done
}

parse_args "$@"

cmd="rclone"
has_cmd "$cmd" && [ -z "$force" ] &&
  die "$cmd already installed, use -force to force reinstallation"

log info "Installing $cmd $version"

tmp_dir="$(mktemp -p "$OPT_PATH" -d "$cmd-install-XXX")"
trap 'rm -rf "$tmp_dir"' EXIT INT TERM

version="v$version"
url="https://github.com/rclone/rclone/releases/download/\
$version/rclone-$version-$platform.zip"
outfile="${url##*/}"

cd "$tmp_dir"
fetch "$url"
extract "$outfile"

xdir="rclone-$version-$platform"
mv "$xdir/rclone" "$BIN_PATH"
mv "$xdir/rclone.1" "$MAN_PATH"
"$BIN_PATH/rclone" completion bash "$CMP_PATH/rclone"

log success "$cmd installed"

