#!/bin/sh
set -e

self="${0%/*}"
[ "$self" = "$0" ] && self="."
. "$self/utils.sh"

usage() {
  cat >&2 <<EOF
Usage: $0 [options]

Options:
  -help      Show this help message
  -force     Force reinstallation
  -version   Version to install (default '$version')
EOF
}

parse_args() {
  platform="x86_64-unknown-linux-musl"
  version="14.1.1"

  while [ $# -gt 0 ]; do
    case "$1" in
      -help)
        usage
        exit 0
        ;;
      -force)
        force="true"
        shift
        ;;
      -version)
        version="$(get_opt "$@")"
        shift 2
        ;;
      -*) die -h "Unknown option '$1'" ;;
      *) shift ;;
    esac
  done
}

parse_args "$@"

cmd="rg"
has_cmd "$cmd" && [ -z "$force" ] &&
  die "$cmd already installed, use -force to force reinstallation"

log info "Installing $cmd $version"

tmp_dir="$(mktemp -p "$OPT_PATH" -d "$cmd-install-XXX")"
trap 'rm -rf "$tmp_dir"' EXIT INT TERM

url="https://github.com/BurntSushi/ripgrep/releases/download/\
$version/ripgrep-$version-$platform.tar.gz"
outfile="${url##*/}"

cd "$tmp_dir"
fetch "$url"
extract "$outfile"

xdir="ripgrep-$version-$platform"
mv "$xdir/rg" "$BIN_PATH"
mv "$xdir/doc/rg.1" "$MAN_PATH"
mv "$xdir/complete/rg.bash" "$CMP_PATH"

log success "$cmd installed"

