#!/bin/sh
set -e

self="${0%/*}"
[ "$self" = "$0" ] && self="."
. "$self/utils.sh"

usage() {
  cat >&2 <<EOF
Usage: $0 [options]

Options:
  -help      Show this help message
  -force     Force reinstallation
  -version   Version to install (default '$version')
EOF
}

parse_args() {
  version="3.5"

  while [ $# -gt 0 ]; do
    case "$1" in
      -help)
        usage
        exit 0
        ;;
      -force)
        force="true"
        shift
        ;;
      -version)
        version="$(get_opt "$@")"
        shift 2
        ;;
      -*) die -h "Unknown option '$1'" ;;
      *) shift ;;
    esac
  done
}

parse_args "$@"

cmd="tmux"
has_cmd "$cmd" && [ -z "$force" ] &&
  die "$cmd already installed, use -force to force reinstallation"

log info "Installing $cmd $version"

tmp_dir="$(mktemp -p "$OPT_PATH" -d "$cmd-install-XXX")"
trap 'rm -rf "$tmp_dir"' EXIT INT TERM

url="https://github.com/BinhPhan13/dev-workspace/releases/download/assets/\
tmux-$version.tar.gz"
outfile="${url##*/}"

cd "$tmp_dir"
fetch "$url"
extract "$outfile"

install tmux -Dt $HOME/.local/bin
install tmux.1 -Dt $HOME/.local/share/man/man1 -m 644

log success "$cmd installed"

