#!/bin/sh
set -e

self="${0%/*}"
[ "$self" = "$0" ] && self="."
. "$self/utils.sh"

usage() {
  cat >&2 <<EOF
Usage: $0 [options]

Options:
  -help      Show this help message
  -force     Force reinstallation
  -version   Version to install (default '$version')
EOF
}

parse_args() {
  version="3.1.0"

  while [ $# -gt 0 ]; do
    case "$1" in
      -help)
        usage
        exit 0
        ;;
      -force)
        force="true"
        shift
        ;;
      -version)
        version="$(get_opt "$@")"
        shift 2
        ;;
      -*) die -h "Unknown option '$1'" ;;
      *) shift ;;
    esac
  done
}

parse_args "$@"

cmd="tpm"
has_cmd "$cmd" && [ -z "$force" ] &&
  die "$cmd already installed, use -force to force reinstallation"

log info "Installing $cmd $version"

dest="$OPT_PATH/$cmd"
[ -e "$dest" ] && rm -r "$dest"

tmp_dir="$(mktemp -p "$OPT_PATH" -d "$cmd-install-XXX")"
trap 'rm -rf "$tmp_dir"' EXIT INT TERM

url="https://github.com/tmux-plugins/tpm/archive/refs/tags/v$version.tar.gz"
outfile="${url##*/}"

cd "$tmp_dir"
fetch "$url"
extract "$outfile"

xdir="tpm-$version"
mv "$xdir" -T "$dest"
install /dev/stdin "$BIN_PATH/$cmd" <<EOF
#!/bin/sh
$dest/tpm
EOF

log success "$cmd installed"

