#!/bin/sh
set -e

self="${0%/*}"
[ "$self" = "$0" ] && self="."
. "$self/utils.sh"

usage() {
  cat >&2 <<EOF
Usage: $0 [options]

Options:
  -help      Show this help message
  -force     Force reinstallation
  -version   Version to install (default '$version')
EOF
}

parse_args() {
  version="0.8.24"

  while [ $# -gt 0 ]; do
    case "$1" in
      -help)
        usage
        exit 0
        ;;
      -force)
        force="true"
        shift
        ;;
      -version)
        version="$(get_opt "$@")"
        shift 2
        ;;
      -*) die -h "Unknown option '$1'" ;;
      *) shift ;;
    esac
  done
}

parse_args "$@"

cmd="uv"
has_cmd "$cmd" && [ -z "$force" ] &&
  die "$cmd already installed, use -force to force reinstallation"

log info "Installing $cmd $version"

need_cmd curl
curl -#fL "https://astral.sh/uv/$version/install.sh" |
  UV_UNMANAGED_INSTALL="$BIN_PATH" sh

"$BIN_PATH/$cmd" generate-shell-completion bash > "$CMP_PATH/$cmd"

log success "$cmd installed"

